// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EmailExtractor.Models
{
    public partial class AutoEmailServers
    {
        public int Id { get; set; }
        public string ServerName { get; set; }
        public bool Verified { get; set; }
        public string EmployeesOutlook { get; set; }
    }
}