// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EmailExtractor.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace EmailExtractor.Models
{
    public partial interface IpPrismMasterContextProcedures
    {
        Task<int> EmailDeleterAsync(string param1, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
