// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EmailServerAPI.Models
{
    public partial class AutoEmail
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Subject { get; set; }
        public DateTime? MailDate { get; set; }
        public string User { get; set; }
    }
}